theme: jekyll-theme-minimal

theme: jekyll-theme-dinky

integration_spreadsheet_key: 2PACX-1vTt1ZO9Hc5NOFHORDUhpwFKc5WndP5ijF7efH1M59BuJrk8h7zQd76wM2IjWL2Y-UkBkpzEjf4aybfL

github_user: lucant
github_repo: TeamDisplay